spring:
  profiles:
    active: prod
  thymeleaf:
    cache: false

github:
  client:
    id: 723ca7c1206fcfbff6cb
    secret: 1d95bd7386cece906dad5112cd3ef0a7a63d550a
  user:
    token: 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

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yiwa.community.pojo,com.yiwa.community.dto
  configuration:
    map-underscore-to-camel-case: true

file:
  upload:
    url: classpath:static/imageUserUpload


logging:
  file:
    path: logs/
    max-size: 1MB
    max-history: 30
  level:
    com.yiwa.community.dao: info



