server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community
    username: yiwa
    password: "********"
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource



