spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false

github:
  client:
    id: 9ccf32dccdbe1ff11422
    secret: 248dea280baf08db093641ec282bc0481fe7ed9b
  user:
    token: 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

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yiwa.community.pojo,com.yiwa.community.dto
  configuration:
    map-underscore-to-camel-case: true

file:
  upload:
    url: classpath:static/imageUserUpload


logging:
  file:
    path: logs/
    max-size: 1MB
    max-history: 30
  level:
    com.yiwa.community.dao: info



